version: "3.7"

services:
  kneesocks:
    image: chop1k/kneesocks
    ports:
      - "1080:1080/tcp"
      - "1080:1080/udp"
    volumes:
      - ./config:/etc/kneesocks
      - logs:/var/log/kneesocks
    networks:
      - kneesocks
    restart: always

networks:
  kneesocks:
    driver: bridge

volumes:
  logs:
    driver: local